version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  redis-client:
    build: ./redis-client
    network_mode: host
    ports:
      - "9000:9000"
    volumes:
      - ./redis-client:/go/src/redis-client
  redis:
    image: redis
    ports:
      - '6379:6379'
